//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficPoliceProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicencesCategories
    {
        public int Id { get; set; }
        public int LicencesId { get; set; }
        public int CategoriesId { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Licences Licences { get; set; }
    }
}
