//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficPoliceProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCode
    {
        public int Id { get; set; }
        public string RegionName_EN_ { get; set; }
        public string RegionName_RU_ { get; set; }
        public int SubjectCode { get; set; }
        public string Code { get; set; }
        public string OKATO { get; set; }
        public string ISO_3166_2 { get; set; }
    }
}
