//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficPoliceProject.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class RoadAccident
    {
        public int Id { get; set; }
        public int DriverId { get; set; }
        public int LicenceId { get; set; }
        public string CrimeScene { get; set; }
        public int ClassificationId { get; set; }
        public int NumberOfVictims { get; set; }
        public System.DateTime DateOfIncident { get; set; }
        public System.DateTime TimeOfIncident { get; set; }

        public virtual Classification Classification { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Licences Licences { get; set; }

        /// <summary>
        /// Получение цветов.
        /// </summary>
        public SolidColorBrush ColorRoadAccident
        {
            get
            {
                if (this.NumberOfVictims < 3)
                    return Brushes.Green;
                if ((this.NumberOfVictims > 3) &&
                    (this.NumberOfVictims < 6))
                    return Brushes.Red;
                if (this.NumberOfVictims > 6)
                    return Brushes.Green;
                else
                    return Brushes.White;
            }
        }

        /// <summary>
        /// Получение даты.
        /// </summary>
        public string ToShortDate
        {
            get => this.DateOfIncident.ToShortDateString();
        }

        /// <summary>
        /// Получение времени.
        /// </summary>
        public string ToShortTime
        {
            get => this.DateOfIncident.ToShortTimeString();
        }
    }
}
