//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficPoliceProject.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrafficPoliceEntities : DbContext
    {
        private static Entities.TrafficPoliceEntities _context;
        public TrafficPoliceEntities()
            : base("name=TrafficPoliceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Создание контекста Базы Данных.
        /// </summary>
        /// <returns> Контекст Базы Данных. </returns>
        public static Entities.TrafficPoliceEntities GetContext()
        {
            if (_context == null)
                _context = new Entities.TrafficPoliceEntities();
            return _context;
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Classification> Classification { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<EngineType> EngineType { get; set; }
        public virtual DbSet<Inspector> Inspector { get; set; }
        public virtual DbSet<Licences> Licences { get; set; }
        public virtual DbSet<LicencesCategories> LicencesCategories { get; set; }
        public virtual DbSet<RegionCode> RegionCode { get; set; }
        public virtual DbSet<RoadAccident> RoadAccident { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfDrive> TypeOfDrive { get; set; }
    }
}
